#!/usr/bin/env python3
"""Generates supabase/migrations/0001_baseline.sql, 0002_constraints.sql and 0008_sensitivity_comments.sql
from the Outgrow handoff pack (schema_draft.sql + seed/picklists.json + seed/action_codes.json).
Run: python3 scripts/build_migrations.py <handoff_dir>   (output is committed; the pack is not needed at runtime)"""
import json, re, sys, pathlib

HANDOFF = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/home/claude/work/outgrow-console-handoff")
OUT = pathlib.Path(__file__).resolve().parent.parent / "supabase" / "migrations"
OUT.mkdir(parents=True, exist_ok=True)

draft = (HANDOFF / "data-model" / "schema_draft.sql").read_text()
picklists = json.loads((HANDOFF / "seed" / "picklists.json").read_text())
action_codes = [a["code"] for a in json.loads((HANDOFF / "seed" / "action_codes.json").read_text())]

# ---------------------------------------------------------------- 0001 baseline
lines = [l for l in draft.splitlines() if not l.startswith("comment on ")]
base = "\n".join(lines)
base = base.replace("create extension if not exists pgcrypto;\n", "")           # gen_random_uuid() is core in PG13+
base = base.replace("  record_id uuid not null,\n", "  record_id text not null,\n")      # audit ids include text keys (plays, lists)
base = base.replace("  published_at timestamptz default now(),\n", "  published_at timestamptz,\n")  # draft wrongly defaulted to now()
base = base.replace("  exited_at date default current_date,\n", "  exited_at date,\n")            # draft wrongly defaulted to today
base = base.replace("  prompt_card_questions text,\n", "  prompt_card_questions text[],\n")
assert "record_id text not null" in base and "published_at timestamptz,\n" in base
assert "exited_at date,\n" in base and "prompt_card_questions text[]" in base
base = "\n".join(l for l in base.splitlines() if l.strip() and not l.startswith("--"))   # drop the prose comments; the data dictionary lives in the pack
# FKs and their (1:1) indexes are emitted as one data-driven block: same constraint/index names as the draft, ~30 KB smaller.
_fk = re.findall(r"^alter table public\.(\w+) add constraint (\w+) foreign key \((\w+)\) references public\.(\w+)\((\w+)\);$", base, re.M)
_ix = re.findall(r"^create index if not exists (\w+) on public\.(\w+)\((\w+)\);$", base, re.M)
assert len(_fk) == len(_ix) == 143 and all(n == f"{t}_{c}_fkey" for t, n, c, _, _ in _fk) and all(n == f"{t}_{c}_idx" for n, t, c in _ix)
assert {(t, c) for t, _, c, _, _ in _fk} == {(t, c) for _, t, c in _ix}
_body = "\n".join(l for l in base.splitlines() if not l.startswith(("alter table public.", "create index if not exists ")))
_list = ",\n".join("    '%s.%s>%s.%s'" % (t, c, rt, rc) for t, _, c, rt, rc in _fk)
_do = ("do $$ declare r text; a text[]; begin\n  foreach r in array array[\n" + _list + "\n  ] loop\n"
       "    a := regexp_split_to_array(r, '[.>]');\n"
       "    execute format('alter table public.%I add constraint %I foreign key (%I) references public.%I(%I)', a[1], a[1]||'_'||a[2]||'_fkey', a[2], a[3], a[4]);\n"
       "    execute format('create index if not exists %I on public.%I(%I)', a[1]||'_'||a[2]||'_idx', a[1], a[2]);\n"
       "  end loop;\nend $$;")
(OUT / "0001_baseline.sql").write_text(
    "-- Baseline: 39 tables + FKs (with 1:1 indexes) from the Outgrow data model (schema_draft.sql), minus column comments.\n"
    "-- Patched: audit_log.record_id text; scorecard_weeks.published_at no default; list_memberships.exited_at no default;\n"
    "-- focus_calendar.prompt_card_questions text[]. Sensitivity comments live in 0008. Table descriptions: see the Outgrow data dictionary.\n" + _body + "\n" + _do + "\n")

# ---------------------------------------------------------------- parse columns / picklist links
tables = {}
for m in re.finditer(r"create table if not exists public\.(\w+) \((.*?)\n\);", base, re.S):
    cols = {}
    for l in m.group(2).splitlines():
        l = l.strip().rstrip(",")
        mm = re.match(r"(\w+) ([\w\[\]\(\),]+)", l)
        if mm and not l.startswith(("primary", "constraint")):
            cols[mm.group(1)] = mm.group(2)
    tables[m.group(1)] = cols

links = []   # (table, column, PL_NAME)
for m in re.finditer(r"comment on column public\.(\w+)\.(\w+) is '((?:[^']|'')*)';", draft):
    t, c, txt = m.groups()
    pm = re.search(r"picklist=(PL_\w+)", txt)
    if pm: links.append((t, c, pm.group(1)))

def values_for(pl):
    if pl == "PL_ACTION_CODE": return action_codes
    if pl == "PL_COUNTRY": return None
    vals = picklists.get(pl)
    if not vals: return None
    if pl == "PL_CHANNEL": vals = [v for v in vals if not v.startswith("(Email")]
    if pl == "PL_ASSIGNMENT_STATUS": vals = vals + ["Draft", "Dropped"]      # delta #1 in docs/05
    return vals

def q(s): return "'" + s.replace("'", "''") + "'"
out = ["-- Generated by scripts/build_migrations.py: CHECK constraints from picklists (docs/05 delta 4).",
       "-- The picklists table stays the admin-editable source for LABELS; these CHECKs guard the values the UI filters on.\n"]
skipped = []
for t, c, pl in links:
    vals = values_for(pl)
    if vals is None or c not in tables.get(t, {}):
        skipped.append((t, c, pl)); continue
    ty = tables[t][c]
    lst = ", ".join(q(v) for v in vals)
    if ty.endswith("[]"):
        out.append(f"alter table public.{t} add constraint chk_{t}_{c} check ({c} is null or {c} <@ array[{lst}]::text[]);")
    else:
        out.append(f"alter table public.{t} add constraint chk_{t}_{c} check ({c} is null or {c} in ({lst}));")

out += ["""
-- Email is not an action channel anywhere (PRD principle 6): explicit, self-documenting guard.
alter table public.touches add constraint chk_touches_no_email check (lower(channel) not like '%email%');
alter table public.contacts add constraint chk_contacts_opt_out_known check (opt_out_channels is null or opt_out_channels <@ array['Call','Voicemail + text','In person','Teams','WhatsApp','KakaoTalk','Video call','SMS','Handwritten note']::text[]);

-- Numeric sanity
alter table public.actions add constraint chk_actions_value_nonneg check (estimated_value_usd >= 0);
alter table public.opportunities add constraint chk_opps_value_nonneg check (estimated_value_usd >= 0);
alter table public.share_of_wallet_readings add constraint chk_sow_pct check (stated_share_pct between 0 and 100);
alter table public.acsia_people add constraint chk_people_target_nonneg check (weekly_target >= 0);
alter table public.contacts add constraint chk_contacts_strength check (relationship_strength is null or relationship_strength between 1 and 5);
alter table public.relationships add constraint chk_rel_strength check (strength between 1 and 5);
alter table public.perseverance_board add constraint chk_persev_rank check (rank >= 1);
alter table public.plays add constraint chk_plays_priority_label check (priority in ('1 - Lead with it','2 - Offer with proof','3 - Learn first (rDYK)'));

-- Defaults so imports and forms do not have to know every NOT NULL
alter table public.touches alter column touch_date set default ((now() at time zone 'Asia/Kolkata')::date);
alter table public.assignments alter column week_start set default ((date_trunc('week', now() at time zone 'Asia/Kolkata'))::date);
alter table public.assignments alter column status set default 'Open';
alter table public.scorecard_weeks alter column status set default 'Draft';
alter table public.touches alter column capture_method set default 'Web';
alter table public.contacts alter column contact_status set default 'Active';
alter table public.acsia_people alter column is_participant set default true;
alter table public.acsia_people alter column show_on_ranked_scorecard set default true;
alter table public.acsia_people alter column logging_mode set default 'Self';
alter table public.acsia_people alter column outgrow_role set default 'Frontline';
alter table public.acsia_people alter column active set default true;
alter table public.acsia_people alter column weekly_target set default 0;
alter table public.service_lines alter column is_lila set default false;
alter table public.service_lines alter column active set default true;
alter table public.service_lines alter column confidence_band set default 'OFFER';
alter table public.capabilities alter column in_portfolio set default true;
alter table public.capabilities alter column do_not_offer set default false;
alter table public.plays alter column version set default 1;
alter table public.plays alter column requires_signoff set default false;
alter table public.plays alter column approval_status set default 'Draft';
alter table public.list_definitions alter column active set default true;
alter table public.testimonials alter column cs_signoff set default false;
alter table public.proof_points alter column approval_status set default 'Draft';
alter table public.insights alter column status set default 'Open';
alter table public.insights alter column ai_extracted set default false;
alter table public.picklists alter column active set default true;

-- Derived fields: computed in views (safe views) instead of stored columns that go stale.
alter table public.accounts drop column if exists days_since_proactive_touch;
alter table public.contacts drop column if exists days_since_proactive_touch;
alter table public.opportunities drop column if exists days_in_stage;
alter table public.opportunities drop column if exists proposal_age_days;
alter table public.list_memberships drop column if exists days_on_list;

-- Audit log: the admin may not have a roster row, so keep the email too.
alter table public.audit_log alter column changed_by_id drop not null;
alter table public.audit_log add column if not exists changed_by_email text;
create index if not exists audit_log_table_record_idx on public.audit_log (table_name, record_id);
create index if not exists audit_log_changed_at_idx on public.audit_log (changed_at desc);

-- Channel rules: match by country code, not by free-text geography.
alter table public.channel_rules add column if not exists country_codes text[];

-- Uniqueness / idempotency
create unique index if not exists picklists_name_value_uidx on public.picklists (picklist_name, value);
create unique index if not exists channel_rules_geography_uidx on public.channel_rules (geography);
create unique index if not exists service_lines_short_code_uidx on public.service_lines (short_code);
create unique index if not exists service_lines_name_uidx on public.service_lines (name);
create unique index if not exists capabilities_sl_name_uidx on public.capabilities (service_line_id, name);
create unique index if not exists competitors_name_uidx on public.competitors (lower(name));
create unique index if not exists focus_calendar_period_uidx on public.focus_calendar (period_type, period_start);
create unique index if not exists scorecard_weeks_week_uidx on public.scorecard_weeks (week_start);
create unique index if not exists person_week_stats_uidx on public.person_week_stats (week_id, person_id);
create unique index if not exists opportunities_source_action_uidx on public.opportunities (source_action_id) where source_action_id is not null;
create unique index if not exists list_memberships_active_uidx on public.list_memberships
  (list_id, account_id, coalesce(contact_id, '00000000-0000-0000-0000-000000000000'::uuid), coalesce(opportunity_id, '00000000-0000-0000-0000-000000000000'::uuid)) where exited_at is null;
create unique index if not exists assignments_week_uidx on public.assignments (week_start, assignee_id, contact_id) where status <> 'Dropped';
create unique index if not exists whitespace_map_uidx on public.whitespace_map
  (account_id, coalesce(org_unit_id, '00000000-0000-0000-0000-000000000000'::uuid), service_line_id) where archived_at is null;
create unique index if not exists accounts_name_uidx on public.accounts (lower(name), country) where archived_at is null;

-- Hot-path indexes not in the baseline
create index if not exists touches_person_date_idx on public.touches (person_id, touch_date desc);
create index if not exists touches_account_date_idx on public.touches (account_id, touch_date desc);
create index if not exists actions_person_date_idx on public.actions (person_id, action_date desc);
create index if not exists actions_code_idx on public.actions (action_code);
create index if not exists assignments_assignee_week_idx on public.assignments (assignee_id, week_start desc);
create index if not exists opportunities_stage_idx on public.opportunities (stage);
create index if not exists contacts_account_idx on public.contacts (account_id);
"""]
(OUT / "0002_constraints.sql").write_text("\n".join(out) + "\n")

# ---------------------------------------------------------------- 0008 sensitivity comments
cm = ["-- Sensitivity tags (Internal-restricted / Personal data) copied from the data dictionary, plus the columns this build classes as",
      "-- restricted (actions.estimated_value_usd, success_stories.value_usd, opportunities.competitor_ids). tests/rls.sql iterates these.\n"]
for m in re.finditer(r"comment on column public\.(\w+\.\w+) is '((?:[^']|'')*)';", draft):
    if "sensitivity=Internal-restricted" in m.group(2) or "sensitivity=Personal data" in m.group(2):
        cm.append(f"comment on column public.{m.group(1)} is '{m.group(2)}';")
cm += ["comment on column public.actions.estimated_value_usd is 'Pipeline value the person typed in the log. | sensitivity=Internal-restricted (added by build)';",
       "comment on column public.success_stories.value_usd is 'Value of the story. | sensitivity=Internal-restricted (added by build)';",
       "comment on column public.opportunities.competitor_ids is 'Competitor intel. | sensitivity=Internal-restricted (added by build)';"]
(OUT / "0008_sensitivity_comments.sql").write_text("\n".join(cm) + "\n")
print("skipped picklist links:", skipped)
print("checks:", sum(1 for l in out if l.startswith("alter table") and "chk_" in l))
