/** Renders the same reference seed as idempotent SQL (insert … on conflict do nothing) → stdout. */
import { buildReferenceSeed, type Row } from "../src/lib/seeds/build";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function lit(v: Row[string], arrType?: "text" | "uuid"): string {
  if (v === null) return "null";
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(",")}]::${arrType ?? "text"}[]` : `'{}'::${arrType ?? "text"}[]`;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return q(v);
}

const out: string[] = ["-- Generated by scripts/seed-to-sql.ts from seed/*.json. Idempotent: existing rows are left alone."];
for (const t of buildReferenceSeed()) {
  const cols = Array.from(new Set(t.rows.flatMap((r) => Object.keys(r))));
  out.push(`\n-- ${t.table} (${t.rows.length})`);
  for (const r of t.rows) {
    const vals = cols.map((c) => lit(r[c] ?? null, t.arrayTypes?.[c]));
    out.push(`insert into public.${t.table} (${cols.join(", ")}) values (${vals.join(", ")}) on conflict (${t.pk}) do nothing;`);
  }
}
console.log(out.join("\n"));
