-- Baseline: 39 tables + FKs (with 1:1 indexes) from the Outgrow data model (schema_draft.sql), minus column comments.
-- Patched: audit_log.record_id text; scorecard_weeks.published_at no default; list_memberships.exited_at no default;
-- focus_calendar.prompt_card_questions text[]. Sensitivity comments live in 0008. Table descriptions: see the Outgrow data dictionary.
create table if not exists public.accounts (
  account_id uuid primary key default gen_random_uuid(),
  name text not null,
  legal_name text,
  parent_account_id uuid,
  account_level text not null,
  relationship_type text not null,
  track text,
  segment text not null,
  vehicle_domain text[],
  region text not null,
  country text not null,
  city_site text,
  web_domain text,
  tier text,
  tier_override boolean,
  customer_status text,
  account_owner_id uuid not null,
  outgrow_owner_id uuid,
  first_won_date date,
  lifetime_billed_usd numeric(14,2),
  ttm_billed_usd numeric(14,2),
  revenue_trend text,
  ext_eng_spend_usd numeric(14,2),
  ext_eng_spend_source text,
  share_of_wallet_pct numeric(7,4),
  service_lines_bought integer,
  buying_committee_est integer,
  contacts_mapped integer,
  coverage_ratio numeric(7,4),
  power_map_status text,
  vendor_panel_status text,
  contract_status text,
  contract_expiry date,
  last_proactive_touch_at timestamptz,
  days_since_proactive_touch integer,
  last_any_interaction_at timestamptz,
  next_planned_touch date,
  lead_play_ids text[],
  strategic_notes text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.org_units (
  org_unit_id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  parent_org_unit_id uuid,
  name text not null,
  function text not null,
  vehicle_domain text,
  site_location text,
  head_contact_id uuid,
  acsia_presence text,
  known_budget_usd numeric(14,2),
  next_sourcing_event date,
  sourcing_notes text,
  discovered_via text,
  discovered_from_action_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.contacts (
  contact_id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  preferred_name text,
  job_title text,
  account_id uuid not null,
  org_unit_id uuid,
  reports_to_contact_id uuid,
  seniority text,
  function text,
  buying_role text,
  influence_level text,
  decision_authority text,
  email text,
  phone_office text,
  phone_mobile text,
  messaging_handle text,
  linkedin_url text,
  country text,
  timezone text,
  language_pref text,
  preferred_channel text,
  opt_out_channels text[],
  legal_basis text,
  contact_status text not null,
  moved_to_contact_id uuid,
  primary_relationship_owner_id uuid,
  relationship_strength integer,
  sentiment text,
  happy_customer_candidate boolean,
  interview_status text,
  testimonial_permission text,
  interests text[],
  rapport_notes text,
  current_priorities text,
  service_lines_dyked uuid[],
  next_recommended_play_id text,
  touch_cadence_days integer,
  last_proactive_touch_at timestamptz,
  days_since_proactive_touch integer,
  next_touch_due date,
  single_thread_risk boolean,
  referred_by_contact_id uuid,
  source text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.contact_positions (
  position_id uuid primary key default gen_random_uuid(),
  contact_id uuid not null,
  account_id uuid not null,
  org_unit_id uuid,
  title text,
  start_date date,
  end_date date,
  is_current boolean,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.acsia_people (
  person_id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  job_role text not null,
  outgrow_role text not null,
  manager_id uuid,
  team_pod text,
  base_location text,
  sme_for_service_lines uuid[],
  is_participant boolean not null,
  participation_start date,
  weekly_target integer not null,
  show_on_ranked_scorecard boolean not null,
  logging_mode text not null,
  languages text[],
  active boolean not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.relationships (
  relationship_id uuid primary key default gen_random_uuid(),
  person_id uuid not null,
  contact_id uuid not null,
  relationship_kind text not null,
  strength integer not null,
  since date,
  last_interaction_at timestamptz,
  is_primary boolean,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.programmes (
  programme_id uuid primary key default gen_random_uuid(),
  name text not null,
  internal_code text,
  contracting_account_id uuid not null,
  end_customer_account_id uuid,
  org_unit_id uuid,
  vehicle_programme text,
  status text not null,
  start_date date,
  planned_end_date date,
  renewal_date date,
  engagement_model text,
  sites text[],
  current_headcount integer,
  monthly_run_rate_usd numeric(14,2),
  delivery_lead_id uuid not null,
  customer_lead_contact_id uuid,
  aspice_processes text[],
  health text,
  health_note text,
  testimonial_eligible boolean,
  source_opportunity_id uuid,
  next_milestone_date date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.programme_services (
  programme_service_id uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  capability_id uuid not null,
  service_line_id uuid,
  is_primary boolean,
  scope_note text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.programme_team (
  programme_team_id uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  person_id uuid not null,
  role_on_programme text,
  on_site boolean,
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.programme_contacts (
  programme_contact_id uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  contact_id uuid not null,
  role text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.milestones (
  milestone_id uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  name text not null,
  milestone_type text not null,
  planned_date date,
  actual_date date,
  status text not null,
  post_call_due date,
  post_call_touch_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.revenue_periods (
  revenue_period_id uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  account_id uuid,
  period_month date not null,
  billed_amount numeric(14,2) not null,
  currency text not null,
  billed_amount_usd numeric(14,2),
  billed_headcount numeric,
  import_batch_id text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.opportunities (
  opportunity_id uuid primary key default gen_random_uuid(),
  name text not null,
  account_id uuid not null,
  org_unit_id uuid,
  primary_contact_id uuid,
  related_programme_id uuid,
  end_customer_account_id uuid,
  service_line_id uuid not null,
  capability_ids uuid[],
  expansion_lever text not null,
  origin text not null,
  source_action_id uuid,
  surfaced_by_id uuid,
  owner_id uuid not null,
  stage text not null,
  stage_changed_at timestamptz not null default now(),
  days_in_stage integer,
  estimated_value_usd numeric(14,2) not null,
  value_basis text not null,
  is_mega_rfq boolean,
  proposal_sent_date date,
  proposal_age_days integer,
  next_step text,
  next_step_date date,
  decision_expected date,
  competitor_ids uuid[],
  closed_date date,
  lost_reason text,
  won_programme_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.whitespace_map (
  whitespace_id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  org_unit_id uuid,
  service_line_id uuid not null,
  status text not null,
  status_source text not null,
  evidence_action_id uuid,
  evidence_insight_id uuid,
  competitor_id uuid,
  est_annual_value_usd numeric(14,2),
  acsia_approved_category text,
  priority text,
  recommended_play_id text,
  last_verified_at date default current_date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.vendor_presence (
  presence_id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  org_unit_id uuid,
  programme_id uuid,
  competitor_id uuid not null,
  service_line_id uuid,
  scope text,
  est_size text,
  position text,
  source text,
  source_action_id uuid,
  first_heard date default current_date,
  last_confirmed date,
  displacement_play_id text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.share_of_wallet_readings (
  reading_id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  org_unit_id uuid,
  scope text not null,
  service_line_id uuid,
  stated_share_pct numeric(7,4) not null,
  stated_by_contact_id uuid not null,
  source_action_id uuid not null,
  where_rest_goes text,
  reading_date date not null default current_date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.service_lines (
  service_line_id uuid primary key default gen_random_uuid(),
  name text not null,
  short_code text not null,
  is_lila boolean not null,
  confidence_band text not null,
  line_card_blurb text,
  sme_owner_id uuid,
  presales_owner_id uuid,
  one_pager_url text,
  active boolean not null,
  sort_order integer,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.capabilities (
  capability_id uuid primary key default gen_random_uuid(),
  service_line_id uuid not null,
  name text not null,
  stack_area text,
  self_rating integer,
  in_portfolio boolean not null,
  do_not_offer boolean not null,
  honest_boundary text,
  delivered_evidence text,
  rating_reviewed_at date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.plays (
  play_id text primary key,
  play_type text not null,
  action_code text not null,
  title text not null,
  from_capability_id uuid,
  from_service_line_id uuid,
  to_service_line_id uuid,
  to_capability_id uuid,
  adjacency_type text,
  script text not null,
  why_it_works text,
  trigger text,
  list_ids text[],
  proof_point_id uuid,
  next_step text,
  priority text not null,
  confidence_band text,
  target_personas text[],
  best_fit_account_ids uuid[],
  geography_notes text,
  requires_signoff boolean not null,
  approval_status text not null,
  approved_by_id uuid,
  approved_at date,
  times_used integer,
  opps_from_play integer,
  version integer not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.proof_points (
  proof_id uuid primary key default gen_random_uuid(),
  title text not null,
  internal_statement text not null,
  external_statement text,
  programme_id uuid,
  end_customer_account_id uuid,
  service_line_ids uuid[] not null,
  approval_status text not null,
  review_due date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.testimonials (
  testimonial_id uuid primary key default gen_random_uuid(),
  interview_id uuid,
  contact_id uuid not null,
  account_id uuid,
  quote_verbatim text not null,
  quote_short text,
  clip_url text,
  clip_start text,
  themes text[],
  service_line_ids uuid[],
  permission_scope text not null,
  cs_signoff boolean not null,
  captured_date date not null default current_date,
  refresh_due date,
  times_shared integer,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.happy_customer_interviews (
  interview_id uuid primary key default gen_random_uuid(),
  cycle text not null,
  contact_id uuid not null,
  account_id uuid,
  interviewer_id uuid not null,
  status text not null,
  scheduled_at timestamptz,
  completed_at timestamptz,
  consent_record boolean,
  consent_use_comments boolean,
  recording_url text,
  transcript_url text,
  suppliers_count integer,
  rank_vs_suppliers text,
  three_words text,
  value_in_their_words text,
  didnt_know_moments text,
  gives_to_others text,
  played_to_team boolean,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.focus_calendar (
  focus_id uuid primary key default gen_random_uuid(),
  period_type text not null,
  period_start date not null,
  period_end date not null,
  dyk_focus_play_ids text[],
  referral_focus text,
  featured_service_line_id uuid,
  prompt_card_questions text[],
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.competitors (
  competitor_id uuid primary key default gen_random_uuid(),
  name text not null,
  competitor_type text not null,
  displacement_play_id text,
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.touches (
  touch_id uuid primary key default gen_random_uuid(),
  touch_date date not null default current_date,
  person_id uuid not null,
  logged_by_id uuid not null,
  account_id uuid not null,
  contact_id uuid,
  programme_id uuid,
  touch_type text not null,
  is_proactive boolean,
  channel text not null,
  customer_response text,
  note text,
  follow_up_date date,
  follow_up_permission boolean,
  assignment_id uuid,
  success_nominated boolean,
  capture_method text not null,
  raw_capture_text text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.actions (
  action_id uuid primary key default gen_random_uuid(),
  touch_id uuid not null,
  action_code text not null,
  service_line_id uuid not null,
  estimated_value_usd numeric(14,2) not null,
  value_stage text,
  play_id text,
  customer_answer text,
  testimonial_id uuid,
  opportunity_id uuid,
  opportunity_created boolean,
  referral_id uuid,
  share_reading_id uuid,
  person_id uuid,
  account_id uuid,
  action_date date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.insights (
  insight_id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  org_unit_id uuid,
  contact_id uuid,
  programme_id uuid,
  insight_type text not null,
  text text not null,
  service_line_ids uuid[],
  source text not null,
  source_touch_id uuid,
  source_interview_id uuid,
  captured_by_id uuid not null,
  captured_at timestamptz not null default now(),
  relevant_until date,
  status text not null,
  converted_opportunity_id uuid,
  ai_extracted boolean not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.referrals (
  referral_id uuid primary key default gen_random_uuid(),
  referral_type text,
  source_action_id uuid not null,
  referring_contact_id uuid not null,
  referred_contact_id uuid,
  referred_name_text text,
  target_account_id uuid,
  target_org_unit_id uuid,
  intro_method text,
  promised_by date,
  status text not null,
  handoff_to_land boolean,
  outcome_opportunity_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.list_definitions (
  list_id text primary key,
  name text not null,
  book_category integer,
  entity text not null,
  rule text not null,
  default_play_id text,
  active boolean not null,
  min_members integer,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.list_memberships (
  membership_id uuid primary key default gen_random_uuid(),
  list_id text not null,
  account_id uuid not null,
  contact_id uuid,
  opportunity_id uuid,
  reason text not null,
  entered_at date not null default current_date,
  exited_at date,
  days_on_list integer,
  assigned_this_week boolean,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.assignments (
  assignment_id uuid primary key default gen_random_uuid(),
  week_start date not null default current_date,
  assignee_id uuid not null,
  assigned_by_id uuid not null,
  meeting_id uuid,
  contact_id uuid not null,
  account_id uuid,
  opportunity_id uuid,
  list_id text,
  expected_action_code text,
  suggested_play_id text,
  instruction text not null,
  due_date date,
  status text not null,
  completed_touch_id uuid,
  skip_reason text,
  coverage_note text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.success_stories (
  story_id uuid primary key default gen_random_uuid(),
  touch_id uuid not null,
  person_id uuid,
  account_id uuid,
  service_line_id uuid,
  story_text text,
  value_usd numeric(14,2),
  status text not null,
  featured_week_id uuid,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.perseverance_board (
  entry_id uuid primary key default gen_random_uuid(),
  scope text not null,
  owner_id uuid not null,
  opportunity_id uuid,
  account_id uuid not null,
  contact_id uuid,
  rank integer not null,
  why text,
  next_action text,
  next_action_date date,
  started_at date not null default current_date,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.scorecard_weeks (
  week_id uuid primary key default gen_random_uuid(),
  week_start date not null default current_date,
  status text not null,
  ceo_commentary text,
  named_person_ids uuid[],
  total_actions integer,
  participation_rate numeric(7,4),
  proposals_raised integer,
  opps_created integer,
  followups_made integer,
  est_value_surfaced_usd numeric(14,2),
  featured_story_ids uuid[],
  featured_testimonial_id uuid,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.person_week_stats (
  person_week_id uuid primary key default gen_random_uuid(),
  week_id uuid not null,
  person_id uuid not null,
  actions integer,
  proactive_touches integer,
  target integer,
  pct_of_target numeric(7,4),
  participated boolean,
  streak_weeks integer,
  rank integer,
  by_code jsonb,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.meetings (
  meeting_id uuid primary key default gen_random_uuid(),
  meeting_type text not null,
  meeting_date date not null,
  facilitator_id uuid not null,
  ceo_attended boolean,
  attendee_ids uuid[],
  participant_id uuid,
  top3_opened text,
  top3_progressed text,
  top3_closed text,
  wallet_share_priorities text,
  measured_rates jsonb,
  decisions text,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.picklists (
  id uuid primary key default gen_random_uuid(),
  picklist_name text not null,
  value text not null,
  label text not null,
  description text,
  sort_order integer,
  active boolean not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.channel_rules (
  rule_id uuid primary key default gen_random_uuid(),
  geography text not null,
  primary_channel text not null,
  follow_up_channel text not null,
  avoid text,
  blocked_channels text[],
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
create table if not exists public.audit_log (
  audit_id uuid primary key default gen_random_uuid(),
  table_name text not null,
  record_id text not null,
  field text,
  old_value text,
  new_value text,
  changed_by_id uuid not null,
  changed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  created_by uuid,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  archived_at timestamptz,
  is_example boolean not null default false
);
do $$ declare r text; a text[]; begin
  foreach r in array array[
    'accounts.parent_account_id>accounts.account_id',
    'accounts.account_owner_id>acsia_people.person_id',
    'accounts.outgrow_owner_id>acsia_people.person_id',
    'org_units.account_id>accounts.account_id',
    'org_units.parent_org_unit_id>org_units.org_unit_id',
    'org_units.head_contact_id>contacts.contact_id',
    'org_units.discovered_from_action_id>actions.action_id',
    'contacts.account_id>accounts.account_id',
    'contacts.org_unit_id>org_units.org_unit_id',
    'contacts.reports_to_contact_id>contacts.contact_id',
    'contacts.moved_to_contact_id>contacts.contact_id',
    'contacts.primary_relationship_owner_id>acsia_people.person_id',
    'contacts.next_recommended_play_id>plays.play_id',
    'contacts.referred_by_contact_id>contacts.contact_id',
    'contact_positions.contact_id>contacts.contact_id',
    'contact_positions.account_id>accounts.account_id',
    'contact_positions.org_unit_id>org_units.org_unit_id',
    'acsia_people.manager_id>acsia_people.person_id',
    'relationships.person_id>acsia_people.person_id',
    'relationships.contact_id>contacts.contact_id',
    'programmes.contracting_account_id>accounts.account_id',
    'programmes.end_customer_account_id>accounts.account_id',
    'programmes.org_unit_id>org_units.org_unit_id',
    'programmes.delivery_lead_id>acsia_people.person_id',
    'programmes.customer_lead_contact_id>contacts.contact_id',
    'programmes.source_opportunity_id>opportunities.opportunity_id',
    'programme_services.programme_id>programmes.programme_id',
    'programme_services.capability_id>capabilities.capability_id',
    'programme_services.service_line_id>service_lines.service_line_id',
    'programme_team.programme_id>programmes.programme_id',
    'programme_team.person_id>acsia_people.person_id',
    'programme_contacts.programme_id>programmes.programme_id',
    'programme_contacts.contact_id>contacts.contact_id',
    'milestones.programme_id>programmes.programme_id',
    'milestones.post_call_touch_id>touches.touch_id',
    'revenue_periods.programme_id>programmes.programme_id',
    'revenue_periods.account_id>accounts.account_id',
    'opportunities.account_id>accounts.account_id',
    'opportunities.org_unit_id>org_units.org_unit_id',
    'opportunities.primary_contact_id>contacts.contact_id',
    'opportunities.related_programme_id>programmes.programme_id',
    'opportunities.end_customer_account_id>accounts.account_id',
    'opportunities.service_line_id>service_lines.service_line_id',
    'opportunities.source_action_id>actions.action_id',
    'opportunities.surfaced_by_id>acsia_people.person_id',
    'opportunities.owner_id>acsia_people.person_id',
    'opportunities.won_programme_id>programmes.programme_id',
    'whitespace_map.account_id>accounts.account_id',
    'whitespace_map.org_unit_id>org_units.org_unit_id',
    'whitespace_map.service_line_id>service_lines.service_line_id',
    'whitespace_map.evidence_action_id>actions.action_id',
    'whitespace_map.evidence_insight_id>insights.insight_id',
    'whitespace_map.competitor_id>competitors.competitor_id',
    'whitespace_map.recommended_play_id>plays.play_id',
    'vendor_presence.account_id>accounts.account_id',
    'vendor_presence.org_unit_id>org_units.org_unit_id',
    'vendor_presence.programme_id>programmes.programme_id',
    'vendor_presence.competitor_id>competitors.competitor_id',
    'vendor_presence.service_line_id>service_lines.service_line_id',
    'vendor_presence.source_action_id>actions.action_id',
    'vendor_presence.displacement_play_id>plays.play_id',
    'share_of_wallet_readings.account_id>accounts.account_id',
    'share_of_wallet_readings.org_unit_id>org_units.org_unit_id',
    'share_of_wallet_readings.service_line_id>service_lines.service_line_id',
    'share_of_wallet_readings.stated_by_contact_id>contacts.contact_id',
    'share_of_wallet_readings.source_action_id>actions.action_id',
    'service_lines.sme_owner_id>acsia_people.person_id',
    'service_lines.presales_owner_id>acsia_people.person_id',
    'capabilities.service_line_id>service_lines.service_line_id',
    'plays.from_capability_id>capabilities.capability_id',
    'plays.from_service_line_id>service_lines.service_line_id',
    'plays.to_service_line_id>service_lines.service_line_id',
    'plays.to_capability_id>capabilities.capability_id',
    'plays.proof_point_id>proof_points.proof_id',
    'plays.approved_by_id>acsia_people.person_id',
    'proof_points.programme_id>programmes.programme_id',
    'proof_points.end_customer_account_id>accounts.account_id',
    'testimonials.interview_id>happy_customer_interviews.interview_id',
    'testimonials.contact_id>contacts.contact_id',
    'testimonials.account_id>accounts.account_id',
    'happy_customer_interviews.contact_id>contacts.contact_id',
    'happy_customer_interviews.account_id>accounts.account_id',
    'happy_customer_interviews.interviewer_id>acsia_people.person_id',
    'focus_calendar.featured_service_line_id>service_lines.service_line_id',
    'competitors.displacement_play_id>plays.play_id',
    'touches.person_id>acsia_people.person_id',
    'touches.logged_by_id>acsia_people.person_id',
    'touches.account_id>accounts.account_id',
    'touches.contact_id>contacts.contact_id',
    'touches.programme_id>programmes.programme_id',
    'touches.assignment_id>assignments.assignment_id',
    'actions.touch_id>touches.touch_id',
    'actions.service_line_id>service_lines.service_line_id',
    'actions.play_id>plays.play_id',
    'actions.testimonial_id>testimonials.testimonial_id',
    'actions.opportunity_id>opportunities.opportunity_id',
    'actions.referral_id>referrals.referral_id',
    'actions.share_reading_id>share_of_wallet_readings.reading_id',
    'actions.person_id>acsia_people.person_id',
    'actions.account_id>accounts.account_id',
    'insights.account_id>accounts.account_id',
    'insights.org_unit_id>org_units.org_unit_id',
    'insights.contact_id>contacts.contact_id',
    'insights.programme_id>programmes.programme_id',
    'insights.source_touch_id>touches.touch_id',
    'insights.source_interview_id>happy_customer_interviews.interview_id',
    'insights.captured_by_id>acsia_people.person_id',
    'insights.converted_opportunity_id>opportunities.opportunity_id',
    'referrals.source_action_id>actions.action_id',
    'referrals.referring_contact_id>contacts.contact_id',
    'referrals.referred_contact_id>contacts.contact_id',
    'referrals.target_account_id>accounts.account_id',
    'referrals.target_org_unit_id>org_units.org_unit_id',
    'referrals.outcome_opportunity_id>opportunities.opportunity_id',
    'list_definitions.default_play_id>plays.play_id',
    'list_memberships.list_id>list_definitions.list_id',
    'list_memberships.account_id>accounts.account_id',
    'list_memberships.contact_id>contacts.contact_id',
    'list_memberships.opportunity_id>opportunities.opportunity_id',
    'assignments.assignee_id>acsia_people.person_id',
    'assignments.assigned_by_id>acsia_people.person_id',
    'assignments.meeting_id>meetings.meeting_id',
    'assignments.contact_id>contacts.contact_id',
    'assignments.account_id>accounts.account_id',
    'assignments.opportunity_id>opportunities.opportunity_id',
    'assignments.list_id>list_definitions.list_id',
    'assignments.suggested_play_id>plays.play_id',
    'assignments.completed_touch_id>touches.touch_id',
    'success_stories.touch_id>touches.touch_id',
    'success_stories.person_id>acsia_people.person_id',
    'success_stories.account_id>accounts.account_id',
    'success_stories.service_line_id>service_lines.service_line_id',
    'success_stories.featured_week_id>scorecard_weeks.week_id',
    'perseverance_board.owner_id>acsia_people.person_id',
    'perseverance_board.opportunity_id>opportunities.opportunity_id',
    'perseverance_board.account_id>accounts.account_id',
    'perseverance_board.contact_id>contacts.contact_id',
    'scorecard_weeks.featured_testimonial_id>testimonials.testimonial_id',
    'person_week_stats.week_id>scorecard_weeks.week_id',
    'person_week_stats.person_id>acsia_people.person_id',
    'meetings.facilitator_id>acsia_people.person_id',
    'meetings.participant_id>acsia_people.person_id',
    'audit_log.changed_by_id>acsia_people.person_id'
  ] loop
    a := regexp_split_to_array(r, '[.>]');
    execute format('alter table public.%I add constraint %I foreign key (%I) references public.%I(%I)', a[1], a[1]||'_'||a[2]||'_fkey', a[2], a[3], a[4]);
    execute format('create index if not exists %I on public.%I(%I)', a[1]||'_'||a[2]||'_idx', a[1], a[2]);
  end loop;
end $$;
