-- Generated by scripts/build_migrations.py: CHECK constraints from picklists (docs/05 delta 4).
-- The picklists table stays the admin-editable source for LABELS; these CHECKs guard the values the UI filters on.

alter table public.accounts add constraint chk_accounts_account_level check (account_level is null or account_level in ('Group', 'Legal entity', 'Site / engineering centre'));
alter table public.accounts add constraint chk_accounts_relationship_type check (relationship_type is null or relationship_type in ('Direct customer', 'End customer via partner', 'Former customer', 'Pipeline only', 'Partner', 'Prospect (LAND)'));
alter table public.accounts add constraint chk_accounts_track check (track is null or track in ('EXPAND', 'LAND', 'MIXED'));
alter table public.accounts add constraint chk_accounts_segment check (segment is null or segment in ('OEM', 'Tier-1', 'Tier-2', 'Engineering services intermediary', 'Tool provider', 'Silicon', 'Other'));
alter table public.accounts add constraint chk_accounts_vehicle_domain check (vehicle_domain is null or vehicle_domain <@ array['Passenger', 'Commercial vehicle', 'Two-wheeler', 'Off-highway', 'Cross-platform']::text[]);
alter table public.accounts add constraint chk_accounts_region check (region is null or region in ('India', 'Germany', 'Rest of EU', 'US', 'Japan', 'South Korea', 'China', 'Other'));
alter table public.accounts add constraint chk_accounts_tier check (tier is null or tier in ('A - top 5', 'B - established', 'C - foothold', 'D - pipeline only'));
alter table public.accounts add constraint chk_accounts_customer_status check (customer_status is null or customer_status in ('Active', 'Dormant', 'Former', 'Pipeline only'));
alter table public.accounts add constraint chk_accounts_revenue_trend check (revenue_trend is null or revenue_trend in ('Growing', 'Flat', 'Decreasing', 'Stopped', 'Not enough data'));
alter table public.accounts add constraint chk_accounts_ext_eng_spend_source check (ext_eng_spend_source is null or ext_eng_spend_source in ('Customer-stated', 'Annual report', 'Analyst / research', 'Internal guess'));
alter table public.accounts add constraint chk_accounts_power_map_status check (power_map_status is null or power_map_status in ('Not started', 'Partial', 'Complete'));
alter table public.accounts add constraint chk_accounts_vendor_panel_status check (vendor_panel_status is null or vendor_panel_status in ('Approved', 'Approved for some categories', 'Registration in progress', 'Not registered', 'Unknown'));
alter table public.accounts add constraint chk_accounts_contract_status check (contract_status is null or contract_status in ('None', 'NDA', 'MSA', 'MSA + rate card'));
alter table public.org_units add constraint chk_org_units_function check (function is null or function in ('V&V / Test', 'Functional safety', 'Cybersecurity', 'Software architecture', 'Platform / BSP', 'Cockpit / HMI / IVI', 'AUTOSAR / ECU software', 'E/E architecture', 'Powertrain / EV', 'ADAS / AD', 'Telematics / connectivity', 'Quality / process (ASPICE)', 'Requirements / systems engineering', 'Tools / DevOps', 'Programme management', 'Procurement', 'R&D / innovation', 'Executive', 'Other'));
alter table public.org_units add constraint chk_org_units_vehicle_domain check (vehicle_domain is null or vehicle_domain in ('Passenger', 'Commercial vehicle', 'Two-wheeler', 'Off-highway', 'Cross-platform'));
alter table public.org_units add constraint chk_org_units_acsia_presence check (acsia_presence is null or acsia_presence in ('Active delivery', 'Past delivery', 'Contact only', 'None known'));
alter table public.org_units add constraint chk_org_units_discovered_via check (discovered_via is null or discovered_via in ('Internal referral', 'rDYK answer', 'Happy-customer interview', 'Research', 'Org chart', 'Delivery team'));
alter table public.contacts add constraint chk_contacts_seniority check (seniority is null or seniority in ('C-level', 'VP', 'Director', 'Head of', 'Manager', 'Lead', 'Engineer'));
alter table public.contacts add constraint chk_contacts_function check (function is null or function in ('V&V / Test', 'Functional safety', 'Cybersecurity', 'Software architecture', 'Platform / BSP', 'Cockpit / HMI / IVI', 'AUTOSAR / ECU software', 'E/E architecture', 'Powertrain / EV', 'ADAS / AD', 'Telematics / connectivity', 'Quality / process (ASPICE)', 'Requirements / systems engineering', 'Tools / DevOps', 'Programme management', 'Procurement', 'R&D / innovation', 'Executive', 'Other'));
alter table public.contacts add constraint chk_contacts_buying_role check (buying_role is null or buying_role in ('Economic buyer', 'Technical buyer', 'User buyer', 'Coach', 'Gatekeeper', 'Unknown'));
alter table public.contacts add constraint chk_contacts_influence_level check (influence_level is null or influence_level in ('High', 'Medium', 'Low'));
alter table public.contacts add constraint chk_contacts_decision_authority check (decision_authority is null or decision_authority in ('Decides', 'Recommends', 'Influences', 'None'));
alter table public.contacts add constraint chk_contacts_language_pref check (language_pref is null or language_pref in ('English', 'German', 'Japanese', 'Korean', 'Mandarin', 'French', 'Italian', 'Swedish', 'Hindi', 'Other'));
alter table public.contacts add constraint chk_contacts_preferred_channel check (preferred_channel is null or preferred_channel in ('Call', 'Voicemail + text', 'In person', 'Teams', 'WhatsApp', 'KakaoTalk', 'Video call', 'SMS', 'Handwritten note'));
alter table public.contacts add constraint chk_contacts_opt_out_channels check (opt_out_channels is null or opt_out_channels <@ array['Call', 'Voicemail + text', 'In person', 'Teams', 'WhatsApp', 'KakaoTalk', 'Video call', 'SMS', 'Handwritten note']::text[]);
alter table public.contacts add constraint chk_contacts_legal_basis check (legal_basis is null or legal_basis in ('Legitimate interest', 'Consent', 'Contract', 'Unknown'));
alter table public.contacts add constraint chk_contacts_contact_status check (contact_status is null or contact_status in ('Active', 'Left company', 'On leave', 'Do not contact'));
alter table public.contacts add constraint chk_contacts_sentiment check (sentiment is null or sentiment in ('Advocate', 'Positive', 'Neutral', 'Cautious', 'Detractor', 'Unknown'));
alter table public.contacts add constraint chk_contacts_interview_status check (interview_status is null or interview_status in ('Not a candidate', 'Candidate', 'Invited', 'Scheduled', 'Done', 'Declined'));
alter table public.contacts add constraint chk_contacts_testimonial_permission check (testimonial_permission is null or testimonial_permission in ('None', 'Internal training only', 'External anonymised', 'External named'));
alter table public.contacts add constraint chk_contacts_source check (source is null or source in ('Delivery', 'Internal referral', 'External referral', 'Happy-customer interview', 'Event', 'LAND handoff', 'Import'));
alter table public.acsia_people add constraint chk_acsia_people_job_role check (job_role is null or job_role in ('Delivery engineer', 'ATG architect', 'Project manager', 'Delivery lead', 'Account executive', 'SDR', 'Pre-sales', 'Marketing', 'Customer success', 'Leadership'));
alter table public.acsia_people add constraint chk_acsia_people_outgrow_role check (outgrow_role is null or outgrow_role in ('Owner (CEO)', 'Outgrow Leader', 'Administrator', 'Team manager', 'Frontline', 'Supporting'));
alter table public.acsia_people add constraint chk_acsia_people_base_location check (base_location is null or base_location in ('India', 'Germany', 'Rest of EU', 'US', 'Japan', 'South Korea', 'China', 'Other'));
alter table public.acsia_people add constraint chk_acsia_people_logging_mode check (logging_mode is null or logging_mode in ('Self', 'Manager proxy', 'Both'));
alter table public.acsia_people add constraint chk_acsia_people_languages check (languages is null or languages <@ array['English', 'German', 'Japanese', 'Korean', 'Mandarin', 'French', 'Italian', 'Swedish', 'Hindi', 'Other']::text[]);
alter table public.relationships add constraint chk_relationships_relationship_kind check (relationship_kind is null or relationship_kind in ('Day-to-day delivery', 'Technical peer', 'Commercial', 'Executive', 'Former colleague'));
alter table public.programmes add constraint chk_programmes_status check (status is null or status in ('Won - not started', 'Active', 'Ramping down', 'Completed', 'On hold', 'Cancelled'));
alter table public.programmes add constraint chk_programmes_engagement_model check (engagement_model is null or engagement_model in ('T&M', 'Fixed price', 'ODC', 'Capacity pool', 'LiLA licence / subscription', 'Mixed'));
alter table public.programmes add constraint chk_programmes_sites check (sites is null or sites <@ array['India', 'Germany', 'Rest of EU', 'US', 'Japan', 'South Korea', 'China', 'Other']::text[]);
alter table public.programmes add constraint chk_programmes_aspice_processes check (aspice_processes is null or aspice_processes <@ array['SYS.1', 'SYS.2', 'SYS.3', 'SYS.4', 'SYS.5', 'SWE.1', 'SWE.2', 'SWE.3', 'SWE.4', 'SWE.5', 'SWE.6', 'SUP', 'MAN']::text[]);
alter table public.programmes add constraint chk_programmes_health check (health is null or health in ('Green', 'Amber', 'Red'));
alter table public.programme_team add constraint chk_programme_team_role_on_programme check (role_on_programme is null or role_on_programme in ('Delivery engineer', 'ATG architect', 'Project manager', 'Delivery lead', 'Account executive', 'SDR', 'Pre-sales', 'Marketing', 'Customer success', 'Leadership'));
alter table public.programme_contacts add constraint chk_programme_contacts_role check (role is null or role in ('Sponsor', 'Customer PM', 'Technical lead', 'Quality', 'Procurement', 'End user'));
alter table public.milestones add constraint chk_milestones_milestone_type check (milestone_type is null or milestone_type in ('SOP', 'Release drop', 'Safety case submission', 'ASPICE audit', 'Phase gate', 'Sprint demo', 'Contract renewal'));
alter table public.milestones add constraint chk_milestones_status check (status is null or status in ('Planned', 'Done', 'Slipped', 'Cancelled'));
alter table public.revenue_periods add constraint chk_revenue_periods_currency check (currency is null or currency in ('USD', 'EUR', 'INR', 'JPY', 'KRW', 'GBP'));
alter table public.opportunities add constraint chk_opportunities_expansion_lever check (expansion_lever is null or expansion_lever in ('New service line (cross-sell)', 'More volume (same scope)', 'New buyer (internal referral)', 'New site / geography', 'Engagement model change', 'Renewal / extension', 'Win-back'));
alter table public.opportunities add constraint chk_opportunities_origin check (origin is null or origin in ('Outgrow action', 'Inbound request', 'RFQ received', 'AE-initiated', 'Partner'));
alter table public.opportunities add constraint chk_opportunities_stage check (stage is null or stage in ('Identified', 'Qualifying', 'Pre-proposal', 'Proposal sent', 'Negotiation', 'Won', 'Lost', 'Parked'));
alter table public.opportunities add constraint chk_opportunities_value_basis check (value_basis is null or value_basis in ('One-off', 'Annualised run-rate', 'Multi-year total'));
alter table public.opportunities add constraint chk_opportunities_lost_reason check (lost_reason is null or lost_reason in ('Price', 'Capability', 'Timing', 'Incumbent', 'No decision', 'Vendor panel / procurement', 'Other'));
alter table public.whitespace_map add constraint chk_whitespace_map_status check (status is null or status in ('Buying from Acsia', 'Held by competitor', 'In-house', 'Need confirmed - unsourced', 'Need likely', 'Not relevant', 'Unknown', 'Acsia can''t offer'));
alter table public.whitespace_map add constraint chk_whitespace_map_status_source check (status_source is null or status_source in ('Derived from programmes', 'rDYK answer', 'Interview', 'Research', 'AE judgement'));
alter table public.whitespace_map add constraint chk_whitespace_map_acsia_approved_category check (acsia_approved_category is null or acsia_approved_category in ('Yes', 'No', 'Unknown'));
alter table public.whitespace_map add constraint chk_whitespace_map_priority check (priority is null or priority in ('1 - Lead with it', '2 - Offer with proof', '3 - Learn first (rDYK)'));
alter table public.vendor_presence add constraint chk_vendor_presence_position check (position is null or position in ('Incumbent', 'Co-supplier', 'Being evaluated', 'Displaced by Acsia', 'Won against Acsia'));
alter table public.vendor_presence add constraint chk_vendor_presence_source check (source is null or source in ('Action', 'Interview', 'Delivery team', 'Lost deal', 'Research', 'News', 'Market intel'));
alter table public.share_of_wallet_readings add constraint chk_share_of_wallet_readings_scope check (scope is null or scope in ('All outsourced engineering', 'One service line', 'One programme'));
alter table public.service_lines add constraint chk_service_lines_confidence_band check (confidence_band is null or confidence_band in ('LEAD', 'OFFER', 'OFFER W/ REF', 'GUARDED', 'DO NOT OFFER'));
alter table public.capabilities add constraint chk_capabilities_stack_area check (stack_area is null or stack_area in ('MCU / AUTOSAR stack', 'SOC platform', 'Application & HMI', 'Safety, security & compliance', 'Connectivity & networking', 'Tooling & observability', 'Integration, V&V & quality', 'Programme & process', 'Media & graphics (gap zone)', 'Platform (LiLA)'));
alter table public.plays add constraint chk_plays_play_type check (play_type is null or play_type in ('DYK', 'Reverse DYK', 'Pivot to sale', 'Pivot to next', '% of business', 'Internal referral', 'External referral', 'Testimonial', 'Voicemail premise', 'Follow-up text', 'List script', 'Displacement probe'));
alter table public.plays add constraint chk_plays_action_code check (action_code is null or action_code in ('OG0.1', 'OG1.1', 'OG1.2', 'OG2.1', 'OG2.2', 'OG2.3', 'OG2.4', 'OG3.1', 'OG4.1', 'OG4.2', 'OG5.1', 'OG6.1'));
alter table public.plays add constraint chk_plays_adjacency_type check (adjacency_type is null or adjacency_type in ('Vertical stack', 'Lifecycle (next phase)', 'Programme twin (other silicon)', 'Toolchain attach', 'Compliance pull', 'Evidence chain', 'Downshift to what Acsia holds', 'Sister platform', 'Off-board twin', 'LiLA standing'));
alter table public.plays add constraint chk_plays_priority check (priority is null or priority in ('1 - Lead with it', '2 - Offer with proof', '3 - Learn first (rDYK)'));
alter table public.plays add constraint chk_plays_confidence_band check (confidence_band is null or confidence_band in ('LEAD', 'OFFER', 'OFFER W/ REF', 'GUARDED', 'DO NOT OFFER'));
alter table public.plays add constraint chk_plays_target_personas check (target_personas is null or target_personas <@ array['V&V / Test', 'Functional safety', 'Cybersecurity', 'Software architecture', 'Platform / BSP', 'Cockpit / HMI / IVI', 'AUTOSAR / ECU software', 'E/E architecture', 'Powertrain / EV', 'ADAS / AD', 'Telematics / connectivity', 'Quality / process (ASPICE)', 'Requirements / systems engineering', 'Tools / DevOps', 'Programme management', 'Procurement', 'R&D / innovation', 'Executive', 'Other']::text[]);
alter table public.plays add constraint chk_plays_approval_status check (approval_status is null or approval_status in ('Draft', 'Approved - internal', 'Approved - external', 'Retired'));
alter table public.proof_points add constraint chk_proof_points_approval_status check (approval_status is null or approval_status in ('Draft', 'Approved - internal', 'Approved - external', 'Retired'));
alter table public.testimonials add constraint chk_testimonials_permission_scope check (permission_scope is null or permission_scope in ('None', 'Internal training only', 'External anonymised', 'External named'));
alter table public.happy_customer_interviews add constraint chk_happy_customer_interviews_status check (status is null or status in ('Not a candidate', 'Candidate', 'Invited', 'Scheduled', 'Done', 'Declined'));
alter table public.focus_calendar add constraint chk_focus_calendar_period_type check (period_type is null or period_type in ('Month', 'Week'));
alter table public.competitors add constraint chk_competitors_competitor_type check (competitor_type is null or competitor_type in ('Engineering services provider', 'Tool vendor', 'In-house team', 'Staffing', 'Silicon vendor services'));
alter table public.touches add constraint chk_touches_touch_type check (touch_type is null or touch_type in ('Proactive call', 'Voicemail + text', 'Unscheduled visit (on site)', 'Scheduled meeting', 'Inbound (customer-initiated)', 'Call-when-emailed', 'Handwritten note'));
alter table public.touches add constraint chk_touches_channel check (channel is null or channel in ('Call', 'Voicemail + text', 'In person', 'Teams', 'WhatsApp', 'KakaoTalk', 'Video call', 'SMS', 'Handwritten note'));
alter table public.touches add constraint chk_touches_customer_response check (customer_response is null or customer_response in ('Positive', 'Neutral', 'Not now', 'No answer', 'Negative'));
alter table public.touches add constraint chk_touches_capture_method check (capture_method is null or capture_method in ('Web', 'Mobile', 'Teams bot', 'Text to manager (AI-parsed)', 'Voice note (AI-parsed)'));
alter table public.actions add constraint chk_actions_action_code check (action_code is null or action_code in ('OG0.1', 'OG1.1', 'OG1.2', 'OG2.1', 'OG2.2', 'OG2.3', 'OG2.4', 'OG3.1', 'OG4.1', 'OG4.2', 'OG5.1', 'OG6.1'));
alter table public.actions add constraint chk_actions_value_stage check (value_stage is null or value_stage in ('Opportunity', 'Proposal', 'Closed'));
alter table public.insights add constraint chk_insights_insight_type check (insight_type is null or insight_type in ('Interest', 'Pain point', 'Priority / initiative', 'Talking point', 'Rapport', 'Account news / signal', 'Sourcing timing', 'Budget', 'Objection', 'Didn''t know you did that', 'Gives to other vendor', 'Rate comparison'));
alter table public.insights add constraint chk_insights_source check (source is null or source in ('Action', 'Interview', 'Delivery team', 'Lost deal', 'Research', 'News', 'Market intel'));
alter table public.insights add constraint chk_insights_status check (status is null or status in ('Open', 'Used in a touch', 'Converted', 'Stale'));
alter table public.referrals add constraint chk_referrals_referral_type check (referral_type is null or referral_type in ('Internal (same account group)', 'External (new logo)'));
alter table public.referrals add constraint chk_referrals_intro_method check (intro_method is null or intro_method in ('They introduce us', 'Use their name', 'We reach out'));
alter table public.referrals add constraint chk_referrals_status check (status is null or status in ('Asked', 'Named', 'Intro promised', 'Intro made', 'Meeting held', 'Opportunity', 'Handed to LAND/AE', 'Dead'));
alter table public.list_definitions add constraint chk_list_definitions_entity check (entity is null or entity in ('Account', 'Contact', 'Opportunity'));
alter table public.assignments add constraint chk_assignments_expected_action_code check (expected_action_code is null or expected_action_code in ('OG0.1', 'OG1.1', 'OG1.2', 'OG2.1', 'OG2.2', 'OG2.3', 'OG2.4', 'OG3.1', 'OG4.1', 'OG4.2', 'OG5.1', 'OG6.1'));
alter table public.assignments add constraint chk_assignments_status check (status is null or status in ('Open', 'Done', 'Partly done', 'Rolled over', 'Skipped', 'Draft', 'Dropped'));
alter table public.success_stories add constraint chk_success_stories_status check (status is null or status in ('Nominated', 'Featured', 'Archived'));
alter table public.perseverance_board add constraint chk_perseverance_board_scope check (scope is null or scope in ('Company Top 10', 'Personal Top 5'));
alter table public.scorecard_weeks add constraint chk_scorecard_weeks_status check (status is null or status in ('Draft', 'Awaiting commentary', 'Published'));
alter table public.meetings add constraint chk_meetings_meeting_type check (meeting_type is null or meeting_type in ('Monday huddle', 'Monthly 1:1', 'Quarterly planning', 'Interview playback'));
alter table public.channel_rules add constraint chk_channel_rules_blocked_channels check (blocked_channels is null or blocked_channels <@ array['Call', 'Voicemail + text', 'In person', 'Teams', 'WhatsApp', 'KakaoTalk', 'Video call', 'SMS', 'Handwritten note']::text[]);

-- Email is not an action channel anywhere (PRD principle 6): explicit, self-documenting guard.
alter table public.touches add constraint chk_touches_no_email check (lower(channel) not like '%email%');
alter table public.contacts add constraint chk_contacts_opt_out_known check (opt_out_channels is null or opt_out_channels <@ array['Call','Voicemail + text','In person','Teams','WhatsApp','KakaoTalk','Video call','SMS','Handwritten note']::text[]);

-- Numeric sanity
alter table public.actions add constraint chk_actions_value_nonneg check (estimated_value_usd >= 0);
alter table public.opportunities add constraint chk_opps_value_nonneg check (estimated_value_usd >= 0);
alter table public.share_of_wallet_readings add constraint chk_sow_pct check (stated_share_pct between 0 and 100);
alter table public.acsia_people add constraint chk_people_target_nonneg check (weekly_target >= 0);
alter table public.contacts add constraint chk_contacts_strength check (relationship_strength is null or relationship_strength between 1 and 5);
alter table public.relationships add constraint chk_rel_strength check (strength between 1 and 5);
alter table public.perseverance_board add constraint chk_persev_rank check (rank >= 1);
alter table public.plays add constraint chk_plays_priority_label check (priority in ('1 - Lead with it','2 - Offer with proof','3 - Learn first (rDYK)'));

-- Defaults so imports and forms do not have to know every NOT NULL
alter table public.touches alter column touch_date set default ((now() at time zone 'Asia/Kolkata')::date);
alter table public.assignments alter column week_start set default ((date_trunc('week', now() at time zone 'Asia/Kolkata'))::date);
alter table public.assignments alter column status set default 'Open';
alter table public.scorecard_weeks alter column status set default 'Draft';
alter table public.touches alter column capture_method set default 'Web';
alter table public.contacts alter column contact_status set default 'Active';
alter table public.acsia_people alter column is_participant set default true;
alter table public.acsia_people alter column show_on_ranked_scorecard set default true;
alter table public.acsia_people alter column logging_mode set default 'Self';
alter table public.acsia_people alter column outgrow_role set default 'Frontline';
alter table public.acsia_people alter column active set default true;
alter table public.acsia_people alter column weekly_target set default 0;
alter table public.service_lines alter column is_lila set default false;
alter table public.service_lines alter column active set default true;
alter table public.service_lines alter column confidence_band set default 'OFFER';
alter table public.capabilities alter column in_portfolio set default true;
alter table public.capabilities alter column do_not_offer set default false;
alter table public.plays alter column version set default 1;
alter table public.plays alter column requires_signoff set default false;
alter table public.plays alter column approval_status set default 'Draft';
alter table public.list_definitions alter column active set default true;
alter table public.testimonials alter column cs_signoff set default false;
alter table public.proof_points alter column approval_status set default 'Draft';
alter table public.insights alter column status set default 'Open';
alter table public.insights alter column ai_extracted set default false;
alter table public.picklists alter column active set default true;

-- Derived fields: computed in views (safe views) instead of stored columns that go stale.
alter table public.accounts drop column if exists days_since_proactive_touch;
alter table public.contacts drop column if exists days_since_proactive_touch;
alter table public.opportunities drop column if exists days_in_stage;
alter table public.opportunities drop column if exists proposal_age_days;
alter table public.list_memberships drop column if exists days_on_list;

-- Audit log: the admin may not have a roster row, so keep the email too.
alter table public.audit_log alter column changed_by_id drop not null;
alter table public.audit_log add column if not exists changed_by_email text;
create index if not exists audit_log_table_record_idx on public.audit_log (table_name, record_id);
create index if not exists audit_log_changed_at_idx on public.audit_log (changed_at desc);

-- Channel rules: match by country code, not by free-text geography.
alter table public.channel_rules add column if not exists country_codes text[];

-- Uniqueness / idempotency
create unique index if not exists picklists_name_value_uidx on public.picklists (picklist_name, value);
create unique index if not exists channel_rules_geography_uidx on public.channel_rules (geography);
create unique index if not exists service_lines_short_code_uidx on public.service_lines (short_code);
create unique index if not exists service_lines_name_uidx on public.service_lines (name);
create unique index if not exists capabilities_sl_name_uidx on public.capabilities (service_line_id, name);
create unique index if not exists competitors_name_uidx on public.competitors (lower(name));
create unique index if not exists focus_calendar_period_uidx on public.focus_calendar (period_type, period_start);
create unique index if not exists scorecard_weeks_week_uidx on public.scorecard_weeks (week_start);
create unique index if not exists person_week_stats_uidx on public.person_week_stats (week_id, person_id);
create unique index if not exists opportunities_source_action_uidx on public.opportunities (source_action_id) where source_action_id is not null;
create unique index if not exists list_memberships_active_uidx on public.list_memberships
  (list_id, account_id, coalesce(contact_id, '00000000-0000-0000-0000-000000000000'::uuid), coalesce(opportunity_id, '00000000-0000-0000-0000-000000000000'::uuid)) where exited_at is null;
create unique index if not exists assignments_week_uidx on public.assignments (week_start, assignee_id, contact_id) where status <> 'Dropped';
create unique index if not exists whitespace_map_uidx on public.whitespace_map
  (account_id, coalesce(org_unit_id, '00000000-0000-0000-0000-000000000000'::uuid), service_line_id) where archived_at is null;
create unique index if not exists accounts_name_uidx on public.accounts (lower(name), country) where archived_at is null;

-- Hot-path indexes not in the baseline
create index if not exists touches_person_date_idx on public.touches (person_id, touch_date desc);
create index if not exists touches_account_date_idx on public.touches (account_id, touch_date desc);
create index if not exists actions_person_date_idx on public.actions (person_id, action_date desc);
create index if not exists actions_code_idx on public.actions (action_code);
create index if not exists assignments_assignee_week_idx on public.assignments (assignee_id, week_start desc);
create index if not exists opportunities_stage_idx on public.opportunities (stage);
create index if not exists contacts_account_idx on public.contacts (account_id);

